path:
  remote_url_base: http://data.bedbase.org/
  text2vec: 'sentence-transformers/all-MiniLM-L6-v2'
  # region2vec: databio/r2v-pretrained-for-search
  region2vec: databio/r2v-encode-hg38
  vec2vec: 'databio/v2v-sentencetransformers-encode'
  umap_model: "https://huggingface.co/databio/bedbase-umap/resolve/main/hg38_umap_umap_model_3_13.joblib"
  sparse_model: "prithivida/Splade_PP_en_v2"
database:
  host: $POSTGRES_HOST
  port: 5432
  password: $POSTGRES_PASSWORD
  user: $POSTGRES_USER
  database: bedbase
qdrant:
  host: $QDRANT_HOST
  port: 6333
  api_key: $QDRANT_API_KEY
  file_collection: bedbase
  text_collection: bed_text
  hybrid_collection: bedbase_sparse_collection
server:
  host: 0.0.0.0
  port: 8000
s3:
  endpoint_url: $AWS_ENDPOINT_URL
  aws_access_key_id: $AWS_ACCESS_KEY_ID
  aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: bedbase
phc:
  namespace: databio
  name: bedbase_all
  tag: default
access_methods:
  http:
    type: 'https'
    description: HTTP compatible path
    # prefix: https://data2.bedbase.org/
    prefix: https://api-dev.bedbase.org/v1/files/
  s3:
    type: 's3'
    description: S3 compatible path
    prefix: s3://data2.bedbase.org/
  local:
    type: 'https'
    description: How to serve local files.
    prefix: /static/
